services:
  postgresql:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    env_file:
      - ./env/postgre.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"