name: frogs_data_source
description: A generic interface for managing frogs.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
