include: package:very_good_analysis/analysis_options.3.0.1.yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    public_member_api_docs: false