name: postgres_frog_data_source
description: postgres implementation of frog data source
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  frogs_data_source:
    path: ../frogs_data_source
  postgres: ^2.4.6
  yaml: ^3.1.1
