name: postgres_frog_data_source
description: postgres implementation of frog data source
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
dependencies:
  postgres: ^2.4.6
